apiVersion: v1
kind: ConfigMap
metadata:
  name: config-configmap
  labels:
    app: {{ include "react-sample.fullname" . }}
data: 
  default.json: |
    {
      "BACKEND_URL": "http://localhost/node-api"
    }
