apiVersion: v1
kind: Secret
metadata:
  name: {{ include "node-api.fullname" . }}
  labels:
    {{- include "node-api.labels" . | nindent 4 }}
stringData:
  DB_NAME: ps_db
  DB_USER: ps_user
  DB_PASS: SecurePassword
  DB_PORT: "5432"
  DB_HOST: postgres-service.postgres.svc.cluster.local
