apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  namespace: o11y
  labels:
    grafana_datasource: 'true' # default value for: sidecar.datasources.label
stringData:
    prometheus.yaml: |
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          orgId: 1
          url: http://prometheus-server.o11y.svc.cluster.local/o11y/prometheus/
        - name: loki
          access: proxy
          type: loki
          url: http://loki-gateway.o11y.svc.cluster.local
          database: ''
          user: ''
          password: ''
          basicAuth: false
          id: 1
          orgId: 1
          readOnly: false
          jsonData:
            keepCookies: []
          typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
          skipTlsVerify: true
